import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {parseDictionary,searchDictionary,compareSignatures,inspectPrompt,compileProject,emptyProject,validateProject,auditDictionary} from '../src/core.mjs';
import {appendRecord,verifyJournal} from '../src/journal.mjs';
const source=await readFile(new URL('../data/dictionary-v2.md',import.meta.url),'utf8');
const sha=createHash('sha256').update(source).digest('hex'),db=parseDictionary(source);
const bound=()=>({version:1,bindings:{objective:'Compare dates',target:'Document A',scope:'Section 2',actor:'Reviewer',revision:'v3'},steps:[{signatureId:'SIG-verify-P-source',property:'Date correspondence',evidence:'Source span and comparison'}]});
test('exact uploaded source fingerprint retained',()=>assert.equal(sha,'1df69d1f70f4cb66fe1fa73b8924e1d8dd06967fe494342f5385291e819cc23f'));
test('every lexical and signature heading accounted for',()=>{assert.equal(db.lexemes.length,794);assert.equal(db.signatures.length,1000);assert.equal(Object.keys(db.contracts).length,20);assert.equal(auditDictionary(db).coverage,true);});
test('every parsed signature maps to exact source lines',()=>{for(const s of db.signatures)assert.equal(s.raw,db.lines.slice(s.start-1,s.end).join('\n'));});
test('all inherited contract references resolve',()=>{for(const s of db.signatures)assert.ok(db.contracts[s.contractRef]);});
test('VERIFY retains external, formal, runtime, and source senses',()=>{for(const x of ['external','formal','runtime','source'])assert.ok(db.bySignature.has('SIG-verify-P-'+x));});
test('exact lookup outranks incidental definition matches',()=>assert.equal(searchDictionary(db,{query:'verify'})[0].lex.term,'VERIFY'));
test('source form lookup handles multiword modifiers',()=>assert.ok(searchDictionary(db,{query:'without exception'}).some(x=>x.lex.term==='WITHOUT-EXCEPTION')));
test('joint facets apply to the same sense, not different senses on a lexeme',()=>{for(const row of searchDictionary(db,{contract:'MODIFIER',origin:'SOURCE_MAPPED_CANDIDATE',axis:'BREADTH'}))for(const s of row.senses){assert.equal(s.contractRef,'MODIFIER');assert.equal(s.origin,'SOURCE_MAPPED_CANDIDATE');assert.equal(s.axis,'BREADTH');}});
test('comparison exposes substantive role and obligation differences',()=>{const rows=compareSignatures(db,['SIG-verify-P-formal','SIG-verify-P-external']);assert.ok(rows.find(r=>r.key==='inputs').different);assert.ok(rows.find(r=>r.key==='obligations').different);assert.equal(rows.find(r=>r.key==='operator').different,false);});
test('prompt inspection matches expression boundaries and retains ambiguous senses',()=>{const r=inspectPrompt(db,'Verify exactly two sources; localization is not LOCALIZE.');assert.ok(r.occurrences.some(x=>x.text==='Verify'&&x.signatureIds.length>1));assert.ok(!r.occurrences.some(x=>x.text==='localiz'));assert.ok(r.occurrences.some(x=>x.text==='LOCALIZE'));});
test('longest match retains nested interpretations',()=>{const r=inspectPrompt(db,'independent evidence');const m=r.occurrences.find(x=>x.text==='independent evidence');assert.ok(m);assert.ok(m.nested.length);});
test('unbound drafts never become bound by requesting strength',()=>{const p=emptyProject();p.bindings.objective='Absolutely rigorously verified';p.steps=[{signatureId:'SIG-verify-P-source',property:'',evidence:''}];const c=compileProject(db,p);assert.equal(c.result.status,'UNBOUND_DRAFT');assert.equal(c.result.execution,'NOT_EXECUTED');});
test('bound export preserves local refinements and inherited authority clauses',()=>{const c=compileProject(db,bound(),sha);assert.equal(c.result.status,'BOUND_DRAFT');assert.match(c.text,/Source span and comparison record/);assert.match(c.text,/Authority requirements:/);assert.match(c.text,/SIG-verify-P-source/);assert.equal(c.result.execution,'NOT_EXECUTED');});
test('unknown senses and malformed imports fail closed',()=>{const p=bound();p.steps[0].signatureId='SIG-fiction';assert.throws(()=>validateProject(db,p));assert.throws(()=>parseDictionary(source.replace('Contract: `TEST`','Contract: `MISSING`')));});
test('project export remains deterministic',()=>assert.deepEqual(compileProject(db,bound(),sha),compileProject(db,bound(),sha)));
test('journal survives export, rejects edits and head truncation, and preserves prior records',async()=>{const p=bound();const a=await appendRecord([],p,'Created');const original=JSON.stringify(a);const b=await appendRecord([a],emptyProject(),'Cleared');assert.equal(JSON.stringify(a),original);const pack={format:'bigdic-journal-v1',sourceHash:sha,head:b.hash,events:[a,b]};assert.deepEqual(await verifyJournal(db,pack,sha),emptyProject());const bad=structuredClone(pack);bad.events[0].project.bindings.target='Other';await assert.rejects(verifyJournal(db,bad,sha));await assert.rejects(verifyJournal(db,{...pack,events:[a]},sha));await assert.rejects(verifyJournal(db,pack,'different source'));});
test('Unicode prompt offsets round trip to original text',()=>{const prompt='🧭 VERIFY, then localize.';for(const x of inspectPrompt(db,prompt).occurrences)assert.equal(prompt.slice(x.start,x.end),x.text);});
test('no-hit search is an empty result rather than a fallback interpretation',()=>assert.deepEqual(searchDictionary(db,{query:'zzzznotawordzzzz'}),[]));
